version: '3.5'

networks:
  balance-sheet-test:
    name: balance-sheet-test

services:
  backend:
    build: ./backend
    ports:
      - "3002:3002"
    depends_on:
      - xero-mock
    networks:
      - balance-sheet-test

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend
    networks:
      - balance-sheet-test

  xero-mock:
    image: jaypeng2015/show-me-the-money
    ports:
      - "3000:3000"
    networks:
      - balance-sheet-test
